### ISSUE TITLE
Variation selectors not stripped?

### ISSUE THREAD

**Issue by isabanin** [mwunsch/rumoji#14]
I noticed that "relaxed" emoji (☺️) on Yosemite is not stripped correctly with rumoji due to a variation selector that Apple added to the character. Hex representation of rumoji encoded string that contains a single "relaxed" emoji therefore looks like this:

http://cl.ly/image/2N1j33442e2u

**Comment by mwunsch** [comment]
I'm not reproducing this. Maybe I'm missing something?

```
irb(main):002:0> Rumoji.encode(Rumoji.decode(':relaxed:'))
=> ":relaxed:"
```
