### ISSUE TITLE
Wrong emoji

### ISSUE THREAD

**Issue by casertap** [mwunsch/rumoji#17]
In my db I have the sad emoji
![Image of sad]
(http://i.imgur.com/Hw8Rd0t.jpg)

But using this code:

````
emojify(Rumoji.encode(comment.content))
````

I get this emoji displayed
![Image of the wrong emoji]
(http://i.imgur.com/FtJHoM5.png)

Usually it work but not for the decoding of this smiley (Have been using the plugin for 2 weeks so I may find other wrong smiley in the future)

Here is the information I could get about the smiley in db:
![Image info]
(http://i.imgur.com/k9LwuIP.jpg)

**Comment by mwunsch** [comment]
This does not appear to be a bug in Rumoji:

```ruby
comment = "oh no!!😢"
Rumoji.encode(comment)
#=> "oh no!!:cry:"
Rumoji.decode(Rumoji.encode(comment))
#=> "oh no!!😢"
Rumoji::Emoji.find(:cry).hex
#=>"1F622"
```

Would seem to me that `emojify` might be the culprit here
