### ISSUE TITLE
Matched colons with no matching emojis should not be replaced

### ISSUE THREAD

**Issue by inket** [mwunsch/rumoji#18]
In the case of a custom CMS which uses colons as syntax, replacing *everything* that's surrounded by 2 colons doesn't seem like a good idea.

Example problematic situation:
```
(rdb:94) Rumoji.decode("this is a link to google: (link:http://google.com)")
"this is a link to google: (link//google.com)"
(rdb:94) Rumoji.decode("this is a link to google:(link:http://google.com)")
"this is a link to googlehttp://google.com)"
(rdb:94) Rumoji.decode("this is a link to google:http://google.com")
"this is a link to google//google.com"
```

Also, in case of a new or custom emoji, the current behavior represents a loss of information:
```
(rdb:94) Rumoji.decode("I'm :happy:")
"I'm "
```

**Comment by inket** [comment]
Just noticed https://github.com/mwunsch/rumoji/pull/13

Please merge and release.

**Comment by mwunsch** [comment]
Closing this issue, going to work on merging #13
