### ISSUE TITLE
Does not match 465 new emoji

### ISSUE THREAD

**Issue by rrshaban** [mwunsch/rumoji#19]
The emoji-cheat-sheet version loaded in the current rumoji does not have [465 emoji](https://github.com/arvida/emoji-cheat-sheet.com/issues/229) defined in [the Unicode standard](http://www.unicode.org/Public/emoji/1.0/emoji-data.txt). 

The real issue is that it doesn't seem that there's a [shorthand](https://github.com/github/gemoji) defined yet for these emoji, so if rumoji were to support them it would need to make them up. What to do? I don't know.

**Comment by mwunsch** [comment]
¯\_(ツ)_/¯

Closing this for now. Rumoji is all about translations between the cheat-sheet markup and the unicode characters. Both need to be supported for this to make any sense at all, unfortunately.
