### ISSUE TITLE
Publish v0.5 ?

### ISSUE THREAD

**Issue by christophemaximin** [mwunsch/rumoji#25]
Hi, very nice gem, thanks for the good stuff.

However it was last published on June 11, 2015, and has had a very significant update since (https://github.com/mwunsch/rumoji/commit/0d5f7db8d313cd6562a35ca8981727df5ce1aba5), can you publish a new version please?

**Comment by mwunsch** [comment]
Hi there! Thanks for your patience! I'll work on getting this released this week!

**Comment by mwunsch** [comment]
https://rubygems.org/gems/rumoji/versions/0.5.0
