### ISSUE TITLE
Support for Unicode 9.0

### ISSUE THREAD

**Issue by msbukkuri** [mwunsch/rumoji#29]
Unicode 9.0 is released on June 21, 2016 => http://emojipedia.org/unicode-9.0/

When will the Rumoji library support this? What is the plan of action here?

@7sun @ericmwalsh

**Comment by msbukkuri** [comment]
@mwunsch Any update on this sir? Are there any plans to update this to handle the new Unicode 9.0 version?

**Comment by mwunsch** [comment]
Rumoji really only handles support to/from cheat codes like those found in Slack, http://emoji.codes, or http://www.webpagefx.com/tools/emoji-cheat-sheet/

If the Unicode 9.0 emoji are part of those cheat sheets, it's straightforward to add those codepoints to the library.

It's unlikely I personally would actively work to add these in anytime in the next month, but I'd happily accept a pull request.
